# set background
feh --bg-scale --no-fehbg ~/Pictures/purple_lion.jpg &

# use numpad
numlockx &

# for notifications
dunst &

# transparency
#picom -b --config ~/.config/picom.conf &

# status bar located in $HOME/.dotfiles/scripts
#dwmbar &

# polybar
#polybar example &

#nm-applet &

# hotkeys
sxhkd &

#bspwm changes cursor to x on some windows, keep it as pointer
xsetroot -cursor_name left_ptr &

#exec i3

#exec dwm

#exec bspwm
