#!/usr/bin/env bash

#volume
if [[ `awk -F"[][]" '/Left:/ { print $4 }' <(amixer sget Master) | grep "off"` ]];
then
    printf " $(awk -F"[][]" '/Left:/ { print $2 }' <(amixer sget Master))";
else
    printf " $(awk -F"[][]" '/Left:/ { print $2 }' <(amixer sget Master))";
fi

