#! /bin/sh

#sxhkd &
polybar example &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           0
bspc config top_padding          20

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc config ignore_ewmh_focus true

bspc rule -a st-256color desktop='^2'
bspc rule -a firefox desktop='^1'
bspc rule -a "Tor Browser" desktop='^4'
bspc rule -a minecraft-launcher desktop='^5'
bspc rule -a "VirtualBox Manager" desktop='^5'
bspc rule -a Vlc desktop='^6'
bspc rule -a feh desktop='^5'
bspc rule -a Zathura desktop='^5' state=tiled

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

