#!/usr/bin/env bash

# script to mount drives and usb

tomount=$(lsblk -lp | grep "part $" | awk '{print $1 " ( " $4 " )"}' | dmenu -c -l 12 -p "Which drive to mount: " | awk '{ print $1}')


if [ -z "$tomount" ];
then
    exit 0
else
    mountpoint=$(find /mnt -type d -maxdepth 1 2> /dev/null | dmenu -c -l 12 -p "Where to mount the drive: " | awk '{print $1}')
    if [ -z "$mountpoint" ];
    then
        exit 0
    else
        password=$(dmenu -c -P -p "Password")
        if [ ! -d "$mountpoint" ];
        then
            mkdir "$mountpoint"
            echo "$password" | sudo -S mount $tomount $mountpoint
        else
            echo "$password" | sudo -S mount $tomount $mountpoint
        fi
        sudo -K
    fi
fi
