#!/usr/bin/env bash

# Originally by : DistroTube
# https://gitlab.com/dwt1/dotfiles/blob/master/.dmenu/dmenu-edit-configs.sh

declare options=("bash
bspwm
dwm
i3
polybar
st
sxhkd
vim")

choice=$(echo -e "${options[@]}" | dmenu -i -p 'Edit a config file: ')

case "$choice" in
	bash)
		choice="$HOME/.dotfiles/.bashrc"
	;;
	bspwm)
		choice="$HOME/.dotfiles/.config/bspwm/bspwmrc"
	;;
	dwm)
		choice="$HOME/dwm/config.h"
	;;
	i3)
		choice="$HOME/.dotfiles/.config/i3wm/config"
	;;
	polybar)
		choice="$HOME/.dotfiles/.config/polybar/config"
	;;
	st)
		choice="$HOME/st/config.h"
	;;
	sxhkd)
		choice="$HOME/.dotfiles/.config/sxhkd/sxhkdrc"
	;;
	vim)
		choice="$HOME/.dotfiles/.vimrc"
	;;
	*)
		exit 1
	;;
esac

st -e vim $choice

exit 0
