require('packer-plugin')
require('keymappings')
require('settings')
require('plugins.coq-config')
require('plugins.lualine-config')
require('plugins.neotree-config')
require('plugins.telescope-config')
